run:
  timeout: 5m
  go: "1.21"

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused
    - errcheck
    - gosimple
    - typecheck

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: otterserve

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0