server:
  host: "localhost"
  port: 1123

auth:
  enabled: false
  username: ""
  password: ""

routes:
  - path: "/"
    directory: "./"

logging:
  level: "info"
  file: ""  # empty means stdout/stderr
